services:
  qbittorrent:
    extends:
      file: ../base.yaml
      service: base
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - authelia
    environment:
      - WEBUI_PORT=8081
    volumes:
      - ${HOME}/.config/svcs/qbittorrent:/config
      - /mnt/drv1/torrent:/downloads
    ports:
      # - 8081:8081
      - 30435:30435
      - 30435:30435/udp
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:8081/api/v2/app/version"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAIN}`)"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.tls.certresolver=letsencrypt"
      - "traefik.http.routers.qbittorrent.middlewares=authelia@docker"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8081"
