services:
  vhserver:
    extends:
      file: ../base.yaml
      service: base
    build:
      context: ./
      network: host
    image: ${USER}/vhserver:latest
    container_name: vhserver
    user: vhserver
    volumes:
      - ${HOME}/.config/svcs/vhserver/common.cfg:/home/vhserver/lgsm/config-lgsm/vhserver/common.cfg:ro
      - ${HOME}/.config/svcs/vhserver/save:/home/vhserver/.config/unity3d/IronGate/Valheim
      - ${HOME}/.config/svcs/vhserver/backup:/home/vhserver/lgsm/backup
      - ${HOME}/.config/svcs/vhserver/log:/home/vhserver/log
      - ${HOME}/.config/svcs/vhserver/gamelog:/home/vhserver/serverfiles/Saved/Logs
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
