services:
  authelia:
    extends:
      file: compose/authelia.yaml
      service: authelia
  authelia_redis:
    extends:
      file: compose/authelia.yaml
      service: authelia_redis

  jellyfin:
    extends:
      file: compose/jellyfin.yaml
      service: jellyfin

  photoprism:
    extends:
      file: compose/photoprism.yaml
      service: photoprism
  photoprism_mariadb:
    extends:
      file: compose/photoprism.yaml
      service: photoprism_mariadb

  portainer:
    extends:
      file: compose/portainer.yaml
      service: portainer

  qbittorrent:
    extends:
      file: compose/qbittorrent.yaml
      service: qbittorrent

  samba:
    extends:
      file: compose/samba.yaml
      service: samba

  shadowsocks:
    extends:
      file: compose/shadowsocks.yaml
      service: shadowsocks

  syncthing:
    extends:
      file: compose/syncthing.yaml
      service: syncthing

  traefik:
    extends:
      file: compose/traefik.yaml
      service: traefik

  vaultwarden:
    extends:
      file: compose/vaultwarden.yaml
      service: vaultwarden

  # vhserver:
  #   extends:
  #     file: compose/vhserver.yaml
  #     service: vhserver

networks:
  svcs_bridge:
    name: svcs_bridge
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      config:
        - subnet: 2001:db8:a::/64
          gateway: 2001:db8:a::1
