services:
  shadowsocks:
    build: ./shadowsocks
    image: shadowsocks:1.12.5
    container_name: shadowsocks
    user: shadowsocks
    volumes:
      - ${HOME}/.config/shadowsocks.json:/home/shadowsocks/.config/shadowsocks.json:ro
    networks:
      - default
    ports:
      - 8388:8388/tcp
      - 8388:8388/udp
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 128M
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "8388"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  syncthing:
    build: ./syncthing
    image: syncthing:1.18.5
    container_name: syncthing
    hostname: ${HOSTNAME}
    user: syncthing
    volumes:
      - ${HOME}/.config/syncthing:/home/syncthing/.config/syncthing
      - /mnt/external:/home/syncthing/data
    networks:
      - default
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1024M
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "8384"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  rtorrent:
    build: ./rtorrent
    image: rtorrent:0.9.8
    container_name: rtorrent
    user: rtorrent
    volumes:
      - ${HOME}/.config/rtorrent:/home/rtorrent
      - /mnt/external/torrent:/home/rtorrent/torrent
    networks:
        - default
    ports:
      - 50000:50000
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1024M
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "50000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  flood:
    build: ./flood
    image: flood:4.7.0
    container_name: flood
    depends_on:
      - rtorrent
    user: node
    volumes:
      - ${HOME}/.config/rtorrent:/home/node/rtorrent
      - /mnt/external/torrent:/home/node/torrent
    networks:
      - default
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 128M
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  default:
    driver: bridge
