services:
  authelia:
    extends:
      file: services/authelia/authelia.yaml
      service: authelia

  jellyfin:
    extends:
      file: services/jellyfin/jellyfin.yaml
      service: jellyfin

  mariadb:
    extends:
      file: services/mariadb/mariadb.yaml
      service: mariadb

  openldap:
    extends:
      file: services/openldap/openldap.yaml
      service: openldap

  photoprism:
    extends:
      file: services/photoprism/photoprism.yaml
      service: photoprism

  portainer:
    extends:
      file: services/portainer/portainer.yaml
      service: portainer

  qbittorrent:
    extends:
      file: services/qbittorrent/qbittorrent.yaml
      service: qbittorrent

  redis:
    extends:
      file: services/redis/redis.yaml
      service: redis

  samba:
    extends:
      file: services/samba/samba.yaml
      service: samba

  shadowsocks:
    extends:
      file: services/shadowsocks/shadowsocks.yaml
      service: shadowsocks

  syncthing:
    extends:
      file: services/syncthing/syncthing.yaml
      service: syncthing

  traefik:
    extends:
      file: services/traefik/traefik.yaml
      service: traefik

  vaultwarden:
    extends:
      file: services/vaultwarden/vaultwarden.yaml
      service: vaultwarden

  # vhserver:
  #   extends:
  #     file: services/lgsm-vhserver/lgsm-vhserver.yaml
  #     service: vhserver

networks:
  svcs_bridge:
    name: svcs_bridge
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      config:
        - subnet: 2001:db8:a::/64
          gateway: 2001:db8:a::1
  # svcs_vlan:
  #   name: svcs_vlan
  #   driver: macvlan
  #   driver_opts:
  #     parent: enp0s31f6
  #   ipam:
  #     config:
  #       - subnet: 192.168.200.0/24
  #         gateway: 192.168.200.1
  #         ip_range: 192.168.200.128/25
  #         aux_addresses:
  #           boxedmilk: 192.168.200.200
