services:
  vaultwarden:
    extends:
      file: ../../base/docker-compose.yaml
      service: base
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - ROCKET_PORT=8080
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
      - YUBICO_CLIENT_ID=${YUBICO_CLIENT_ID}
      - YUBICO_SECRET_KEY=${YUBICO_SECRET_KEY}
    volumes:
      - ${HOME}/.config/vaultwarden:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.${DOMAIN}`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=8080"
