services:
  syncthing:
    extends:
      file: ../../base/docker-compose.yaml
      service: base
    build: ./
    image: ${USER}/syncthing:1.19.2
    container_name: syncthing
    user: syncthing
    volumes:
      - ${HOME}/.config/syncthing:/home/syncthing/.config/syncthing
      - /mnt/drv0:/home/syncthing/data
    ports:
      - 22000:22000
      - 22000:22000/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.${DOMAIN}`)"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.tls.certresolver=letsencrypt"
      - "traefik.http.routers.syncthing.middlewares=authelia@docker"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
