services:
  traefik:
    extends:
      file: ../base.yaml
      service: base
    image: traefik:latest
    container_name: traefik
    depends_on:
      - authelia
    command:
      - --configFile=/traefik/traefik.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/.config/svcs/traefik:/traefik
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    ports:
      - 443:443
    healthcheck:
      test: ["CMD-SHELL", "traefik healthcheck --ping"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.middlewares=authelia@docker"
