services:
  authelia:
    extends:
      file: _common.yaml
      service: common
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - ${HOME}/.config/authelia:/config
    depends_on:
      - authelia_redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`login.${DOMAIN}`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls.certresolver=letsencrypt"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.${DOMAIN}/"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email"
      - "traefik.http.middlewares.authelia-basic.forwardauth.address=http://authelia:9091/api/verify?auth=basic"
      - "traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email"

  authelia_redis:
    extends:
      file: _common.yaml
      service: common
    build: ../redis
    image: ${USER}/redis:6-bullseye
    container_name: authelia_redis
    volumes:
      - ${HOME}/.config/authelia/redis:/data
