services:
  portainer:
    extends:
      file: _common.yaml
      service: common
    image: portainer/portainer-ce:linux-amd64-2.11.1-alpine
    container_name: portainer
    volumes:
      - ${HOME}/.config/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
