services:
  vaultwarden:
    extends:
      file: _common.yaml
      service: common
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - ROCKET_PORT=8080
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
      - YUBICO_CLIENT_ID=${YUBICO_CLIENT_ID}
      - YUBICO_SECRET_KEY=${YUBICO_SECRET_KEY}
    volumes:
      - ${HOME}/.config/vaultwarden:/data
