services:
  jellyfin:
    extends:
      file: ../base.yaml
      service: base
    build:
      context: ./
      network: host
    image: ${USER}/jellyfin:10.8.0b2
    container_name: jellyfin
    user: jellyfin
    depends_on:
      - authelia
      - openldap
      - traefik
    group_add:
      - "39"
      - "105"
    volumes:
      - ${HOME}/.config/svcs/jellyfin:/home/jellyfin/.config
      - /mnt/drv1/torrent:/media:ro
    devices:
      - /dev/dri:/dev/dri
    ports:
      # - 8086:8086
      - 1900:1900/udp
      - 7359:7359/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jellyfin.middlewares=authelia@docker"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
