services:
  redis:
    extends:
      file: ../base.yaml
      service: base
    image: bitnami/redis:latest
    container_name: redis
    volumes:
      - ${HOME}/.config/svcs/redis/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - ${HOME}/.config/svcs/redis/users.acl:/opt/bitnami/redis/mounted-etc/users.acl
      - ${HOME}/.config/svcs/redis/data:/bitnami/redis/data
    environment:
      - REDIS_PORT_NUMBER=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_ACLFILE=/opt/bitnami/redis/mounted-etc/users.acl
    # ports:
    #   - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
