services:
  mariadb:
    extends:
      file: ../base.yaml
      service: base
    image: bitnami/mariadb:latest
    container_name: mariadb
    volumes:
      - ${HOME}/.config/svcs/mariadb:/bitnami/mariadb
      - ${HOME}/.config/svcs/mariadb/my.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      # First time envs
      - MARIADB_SKIP_TEST_DB=yes
      - MARIADB_DATABASE=photoprism
      - MARIADB_USER=photoprism
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    # ports:
    #   - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "ps -aux | grep -v grep | grep mysqld"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
