services:
  mariadb:
    extends:
      file: ../../base/docker-compose.yaml
      service: base
    image: mariadb:10.7-focal
    container_name: mariadb
    user: ${UID}:${GID}
    command: mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - ${HOME}/.config/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=photoprism
      - MYSQL_USER=photoprism
      - MYSQL_PASSWORD=${PHOTOPRISM_DATABASE_PASSWORD}
