services:
  mariadb:
    extends:
      file: ../base.yaml
      service: base
    image: bitnami/mariadb:latest
    container_name: mariadb
    volumes:
      - ${HOME}/.config/svcs/mariadb:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      # First time envs
      # - MARIADB_SKIP_TEST_DB=yes
      # - MARIADB_DATABASE=
      # - MARIADB_USER=
      # - MARIADB_PASSWORD=${MARIADB_PASSWORD}
