services:
  shadowsocks:
    extends:
      file: ../../base/docker-compose.yaml
      service: base
    build:
      context: ./
      network: host
    image: ${USER}/shadowsocks:1.14.3
    container_name: shadowsocks
    user: shadowsocks
    volumes:
      - ${HOME}/.config/shadowsocks.json:/home/shadowsocks/.config/shadowsocks.json:ro
    ports:
      - 8388:8388
      - 8388:8388/udp
